In [2]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [ ]:
A = np.array([[2, -1, 4], 
              [0, 5, -2]])

c = 3
print(c*A)

[[ 6 -3 12]
 [ 0 15 -6]]


In [6]:
A = np.array([[2, -1, 4], 
              [0, 5, -2]])
              
B = np.array([[1, -1, 2], 
              [7, 0, 8]])

print(A+B)

[[ 3 -2  6]
 [ 7  5  6]]


In [31]:
A = np.array([[2, -1, 4], 
              [0, 5, -2]])
              
B = np.array([[1, -1], 
              [7, 0]])
print(A+B)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [44]:
# Matrix multiplication example: (4x2) @ (2x3) = (4x3)
A = np.array([[1, 2], 
              [3, 4],
              [5, 6],
              [7, 8]])
B = np.array([[2, 1, 0], 
              [3, 2, 1]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = A @ B
print(f"C has shape {C.shape}")
print(C)

A has shape (4, 2)
B has shape (2, 3)
C has shape (4, 3)
[[ 8  5  2]
 [18 11  4]
 [28 17  6]
 [38 23  8]]


In [45]:
A = np.array([[1, 2], 
              [3, 4],
              [5, 6]])
B = np.array([[2, 1, 0], 
              [3, 2, 1]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = A @ B
print(f"C has shape {C.shape}")
print(C)

A has shape (3, 2)
B has shape (2, 3)
C has shape (3, 3)
[[ 8  5  2]
 [18 11  4]
 [28 17  6]]


In [47]:
A = np.array([[1, 2], 
              [3, 4],
              [5, 6]])
B = np.array([[2, 1, 0], 
              [3, 2, 1]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = B @ A
print(f"C has shape {C.shape}")
print(C)

A has shape (3, 2)
B has shape (2, 3)
C has shape (2, 2)
[[ 5  8]
 [14 20]]


In [46]:
A = np.array([[1, 2, 8], 
              [3, 4, 4],
              [5, 6, 3]])
B = np.array([[2, 1, 0], 
              [3, 2, 1]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = A @ B
print(f"C has shape {C.shape}")
print(C)

A has shape (3, 3)
B has shape (2, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [49]:
A = np.array([[1, 2, 8], 
              [3, 4, 4],
              [5, 6, 3]])
B = np.array([[2, 1, 0], 
              [3, 2, 1],
              [0, 9, 7]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = A @ B
print(f"C has shape {C.shape}")
print(C)

A has shape (3, 3)
B has shape (3, 3)
C has shape (3, 3)
[[ 8 77 58]
 [18 47 32]
 [28 44 27]]


In [50]:
A = np.array([[1, 2, 8], 
              [3, 4, 4],
              [5, 6, 3]])
B = np.array([[2, 1, 0], 
              [3, 2, 1],
              [0, 9, 7]])
print(f"A has shape {A.shape}")
print(f"B has shape {B.shape}")
C = B @ A
print(f"C has shape {C.shape}")
print(C)

A has shape (3, 3)
B has shape (3, 3)
C has shape (3, 3)
[[ 5  8 20]
 [14 20 35]
 [62 78 57]]


In [27]:
linalg.inv(A)

ValueError: expected square matrix

In [21]:
from scipy import linalg
A = np.array([
    [1, 3, 4], 
    [4, -1, 8],
    [-1, -4, 1]
    ])
b = np.array([[8],[-4],[12]])
x = linalg.inv(A) @ b

In [22]:
x

array([[-9.04109589],
       [ 0.2739726 ],
       [ 4.05479452]])

In [23]:
A = np.array([[2, 1], [1, -1]])
b = np.array([4, 1])
x = linalg.solve(A, b) # Solves Ax = b for x

In [24]:
x

array([1.66666667, 0.66666667])

In [55]:
A = np.array([
    [1, 3, 4], 
    [4, -2, 8],
    [-1, -4, 1]])
b = np.array([
    [8], 
    [-4],
    [2]])
x1 = linalg.inv(A) @ b # Solves Ax = b for x    
x2 = linalg.solve(A, b) # Solves Ax = b for x

In [56]:
print(x1)
print(x2)

[[-4.87179487]
 [ 1.28205128]
 [ 2.25641026]]
[[-4.87179487]
 [ 1.28205128]
 [ 2.25641026]]


In [57]:
A@x1

array([[ 8.],
       [-4.],
       [ 2.]])

In [58]:
A = np.array([
    [1, 3, 4], 
    [4, -2, 8],
    [8, -4, 16]])
b = np.array([
    [8], 
    [-4],
    [2]])
x1 = linalg.inv(A) @ b # Solves Ax = b for x    
# x2 = linalg.solve(A, b) # Solves Ax = b for x

LinAlgError: singular matrix

System of 3 masses and interconnected springs

In [121]:
ka = 100 # N/mm
kb = 100 # N/mm
kc = 100 # N/mm
kd = 100 # N/mm

m1 = 200 # kg
m2 = 100 # kg
m3 = 100 # kg

g = 9.81 # m/s/s

a_r1 = [ka+kb, -kb, 0]
a_r2 = [-kb, kb+kc+kd, -kd]
a_r3 = [0, -kd, kd]

A = np.array([a_r1, a_r2, a_r3])

b = [m1*g, m2*g, m3*g]

x = linalg.solve(A, b) # mm
print(x)

[19.62 19.62 29.43]


In [122]:
print(b)

[1962.0, 981.0, 981.0]


In [127]:
k = 10 # N/m
m1, m2, m3 = 2, 3, 2.5 # kg
g = 9.81 # m/s/s

A = k * np.array([
    [3, -2, 0],
    [-2, 3, -1],
    [0, -1, 1]])
print(A)
b = [m1*g, m2*g, m3*g]
print(b)
x = linalg.solve(A, b)
print(x)

[[ 30 -20   0]
 [-20  30 -10]
 [  0 -10  10]]
[19.62, 29.43, 24.525000000000002]
[ 7.3575  10.05525 12.50775]


In [128]:
k = 10 # N/m
m1, m2, m3 = 2, 3, 2.5 # kg
g = 9.81 # m/s/s

A = k * np.array([
    [0, -2, 0],
    [0, 3, -1],
    [0, -1, 1]])
b = [m1*g, m2*g, m3*g]
x = linalg.solve(A, b)
print(x)

LinAlgError: Matrix is singular.